### ISSUE TITLE
[Test] Bug reported

### ISSUE THREAD

**Issue by ashika112** [jimblanc/amplify-js#7]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Version

v6

### Amplify Categories

auth

### Backend

None

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

Buggy code

### Expected behavior

not buggy

### Reproduction steps

do this

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by jimblanc** [comment]
Maintainer commenting

**Comment by ashika112** [comment]
Bug still exists

**Comment by jimblanc** [comment]
This is a bug, triaging

**Comment by jimblanc** [comment]
Closing ticket.
